readme file filled
StanislavYurchenko/qa-test-app pull request #2
Opened 2021-04-03 13:38 UTC by StanislavYurchenko

https://trello.com/c/Ajv9YiQd/1-api-app-fill-readmemd

2021-04-03 13:58 UTC, vovababych reviewed
Может надо или  всех - Full Stack Developer
или если ты хотел написать кто над чем работал - то просто FrontEnd или BackEnd + Team Lead/Scram master, например:
[Stanislav Yurchenko](https://github.com/StanislavYurchenko) - Team lead, Frontend

2021-04-03 14:03 UTC, RomanVoznyy commented
Я тоже за то, чтобы всех назвать FullStackDeveloper, и добавить role - TeamLead, ScrumMaster или Developer.

2021-04-03 17:22 UTC, vovababych requested changes
look in the comments

2021-04-06 12:33 UTC, Andriy1982 approved these changes

2021-04-06 12:58 UTC, vovababych approved these changes

2021-04-06 14:57 UTC, merged